### ISSUE TITLE
Make signUp, signIn, and stake UX flawless

### ISSUE THREAD

**Issue by ccali11** [consensusnetworks/casimir#311]
**Description**
In preparation for alpha/beta testing, we want to assure the expected UX for signIn, signUp, and staking works flawlessly. This task mentions a few "loose end" tasks (below), but also is a blanket task to make sure that a new user does not confront any foreseeable hang-ups in using our service.

**Subtasks**
- [x] Write methods to get balance at each address associated with a user
- [x] Log user out with each new browser session (for quicker dev experience)
- [x] Fix Ledger emulator bug preventing from running at all
- [x] Fix Trezor emulator bug preventing from running at all
- [x] Work through v1 Multi-Account design #304 
- [x] Revisit and include any web3 auth best practices (review and incorporate EIP 1559 and compare our process with SpruceID)
- [x] Handle multiple accounts on Ledger
- [x] Enable Trezor login with multiple accounts
- [x] Fix CoinbaseWallet bugs (some of which are logged [here](https://github.com/consensusnetworks/casimir/issues/246) and [here](https://github.com/consensusnetworks/casimir/issues/281)).
- [x] Add more wallets?

**Comment by ccali11** [comment]
Closing this out for now! Pretty pumped about where we've gotten so far. I'm sure new things will come up as we begin to integrate the new UI with this and will definitely address then. @shanejearley @DemogorGod
